// <auto-generated />
using System;
using CharityAuction.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CharityAuction.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250428075610_AddIsApproved")]
    partial class AddIsApproved
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CharityAuction.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CommissionBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7b26038d-1a43-4248-90e1-dc7f0381d7fa",
                            AccessFailedCount = 0,
                            Balance = 5000m,
                            CommissionBalance = 500m,
                            ConcurrencyStamp = "aac267e7-24a9-4448-a34e-ee66fceb06d5",
                            CreatedAt = new DateTime(2024, 10, 28, 7, 56, 10, 132, DateTimeKind.Utc).AddTicks(9540),
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN.USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEN2VQlyiVSbTnPe807uUAPy/am9hdVepwkLxFCtghXdddEiS9KhSScN6iad/iZs91g==",
                            PhoneNumberConfirmed = false,
                            PhotoUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1.jpg",
                            Role = "admin",
                            SecurityStamp = "e3ab49cd-8133-46cc-9740-774209fac9d7",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 4, 28, 7, 56, 10, 132, DateTimeKind.Utc).AddTicks(9540),
                            UserName = "admin.user"
                        },
                        new
                        {
                            Id = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            AccessFailedCount = 0,
                            Balance = 3000m,
                            CommissionBalance = 300m,
                            ConcurrencyStamp = "fec7b9f1-82a7-4ae0-8259-4226efdf9207",
                            CreatedAt = new DateTime(2024, 10, 28, 7, 56, 10, 132, DateTimeKind.Utc).AddTicks(9540),
                            Email = "seller@example.com",
                            EmailConfirmed = true,
                            FirstName = "Seller",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "SELLER@EXAMPLE.COM",
                            NormalizedUserName = "SELLER.USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEPQHawYqyeu37k2m5G2AczGcbxXpSJCpVeZF4bLAz1kncuUb8rZvcBpzkZrP9xuT1g==",
                            PhoneNumberConfirmed = false,
                            PhotoUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/2.jpg",
                            Role = "seller",
                            SecurityStamp = "802e1ae1-e9fd-44b4-a1fb-39a4bb669d29",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 4, 28, 7, 56, 10, 132, DateTimeKind.Utc).AddTicks(9540),
                            UserName = "seller.user"
                        },
                        new
                        {
                            Id = "62a7c1cd-e93a-4aab-a8a4-64e22210c77f",
                            AccessFailedCount = 0,
                            Balance = 4000m,
                            CommissionBalance = 100m,
                            ConcurrencyStamp = "97834df6-0ea2-43aa-a0cc-b151749a2454",
                            CreatedAt = new DateTime(2024, 10, 28, 7, 56, 10, 132, DateTimeKind.Utc).AddTicks(9540),
                            Email = "buyer1@example.com",
                            EmailConfirmed = true,
                            FirstName = "Buyer",
                            LastName = "One",
                            LockoutEnabled = false,
                            NormalizedEmail = "BUYER1@EXAMPLE.COM",
                            NormalizedUserName = "BUYER.ONE",
                            PasswordHash = "AQAAAAIAAYagAAAAEM2GMbDCeaIZJD6rHw7NUFs42xnrHDUnZEP5srJKUAptxm4ym7FuhwCoNhHds5oofw==",
                            PhoneNumberConfirmed = false,
                            PhotoUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/3.jpg",
                            Role = "buyer",
                            SecurityStamp = "c078afae-9243-4d50-9e79-08189e952e3c",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 4, 28, 7, 56, 10, 132, DateTimeKind.Utc).AddTicks(9540),
                            UserName = "buyer.one"
                        },
                        new
                        {
                            Id = "e034755d-65a9-4f2b-a661-556edac6a6b0",
                            AccessFailedCount = 0,
                            Balance = 2500m,
                            CommissionBalance = 150m,
                            ConcurrencyStamp = "f0d30ce3-20cc-49be-8611-e1b6693dac1d",
                            CreatedAt = new DateTime(2024, 10, 28, 7, 56, 10, 132, DateTimeKind.Utc).AddTicks(9540),
                            Email = "buyer2@example.com",
                            EmailConfirmed = true,
                            FirstName = "Buyer",
                            LastName = "Two",
                            LockoutEnabled = false,
                            NormalizedEmail = "BUYER2@EXAMPLE.COM",
                            NormalizedUserName = "BUYER.TWO",
                            PasswordHash = "AQAAAAIAAYagAAAAEI2Yycbvg4RXLOQ0y0VZRlP8NudV8ZvKHDOG0qMghDj7jtTpc2ZC4yraX9YuOkKFlg==",
                            PhoneNumberConfirmed = false,
                            PhotoUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/4.jpg",
                            Role = "buyer",
                            SecurityStamp = "6698d276-17af-4401-9b30-217ef10f79d4",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 4, 28, 7, 56, 10, 132, DateTimeKind.Utc).AddTicks(9540),
                            UserName = "buyer.two"
                        },
                        new
                        {
                            Id = "2a8da342-5a30-4c2a-a9f2-77bb6659c25f",
                            AccessFailedCount = 0,
                            Balance = 3500m,
                            CommissionBalance = 200m,
                            ConcurrencyStamp = "753fbee7-3068-4213-a634-d3fa34740247",
                            CreatedAt = new DateTime(2024, 10, 28, 7, 56, 10, 132, DateTimeKind.Utc).AddTicks(9540),
                            Email = "buyer3@example.com",
                            EmailConfirmed = true,
                            FirstName = "Buyer",
                            LastName = "Three",
                            LockoutEnabled = false,
                            NormalizedEmail = "BUYER3@EXAMPLE.COM",
                            NormalizedUserName = "BUYER.THREE",
                            PasswordHash = "AQAAAAIAAYagAAAAEHlUj7rBeC066v7F/oeQasFz7TaJCGg6RQ/fOTIRvqIgJSgArVR0AJei+KCGIibzEQ==",
                            PhoneNumberConfirmed = false,
                            PhotoUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/5.jpg",
                            Role = "buyer",
                            SecurityStamp = "ba9917e8-64a2-43bb-ba7c-3dba791b12cc",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 4, 28, 7, 56, 10, 132, DateTimeKind.Utc).AddTicks(9540),
                            UserName = "buyer.three"
                        });
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSold")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganizerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db2b8c40-60c7-4ed1-a6cb-393be4444f77"),
                            CreatedAt = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            Description = "Пускова установка в ідеальному стані для бойових завдань.",
                            EndTime = new DateTime(2025, 5, 5, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            ImageUrl = "https://i.postimg.cc/9rFs09QD/bazuka.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            StartingPrice = 5000m,
                            Title = "Базука"
                        },
                        new
                        {
                            Id = new Guid("29fe88ee-701c-42c3-9a4f-7d1926d1c23f"),
                            CreatedAt = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            Description = "Оптичний бінокль для спостереження на великій відстані.",
                            EndTime = new DateTime(2025, 5, 5, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            ImageUrl = "https://i.postimg.cc/Tp7FDPKC/binokl.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            StartingPrice = 800m,
                            Title = "Бінокль"
                        },
                        new
                        {
                            Id = new Guid("d09c2220-669a-401b-8f6a-4f4f114329df"),
                            CreatedAt = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            Description = "Тактична кобура Blackhawk для зручного носіння зброї.",
                            EndTime = new DateTime(2025, 5, 5, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            ImageUrl = "https://i.postimg.cc/d7dxpm4x/kobura-blackhawk.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            StartingPrice = 1200m,
                            Title = "Кобура Blackhawk"
                        },
                        new
                        {
                            Id = new Guid("6309e613-c9d2-4bbc-b0b6-546d82d27be5"),
                            CreatedAt = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            Description = "Легендарний радянський гранатомет РПГ-18 \"Муха\".",
                            EndTime = new DateTime(2025, 5, 5, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            ImageUrl = "https://i.postimg.cc/0zz3dqmx/RPG-18-Mukha.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            StartingPrice = 7000m,
                            Title = "РПГ-18 Муха"
                        },
                        new
                        {
                            Id = new Guid("803387b4-afb3-4fcb-840a-9dd9f63fc841"),
                            CreatedAt = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            Description = "Оригінальна фуражка з комплекту екіпіровки окупантів.",
                            EndTime = new DateTime(2025, 5, 5, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            ImageUrl = "https://i.postimg.cc/87xYZnBv/russian-cap.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            StartingPrice = 500m,
                            Title = "Фуражка російської армії"
                        },
                        new
                        {
                            Id = new Guid("fe807746-bf07-4157-aaf4-f157ff3c6f2a"),
                            CreatedAt = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            Description = "Типова польова сумка орків, знайдена на передовій.",
                            EndTime = new DateTime(2025, 5, 5, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            ImageUrl = "https://i.postimg.cc/K3cpKXF6/russian-orkivska-sumka.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            StartingPrice = 400m,
                            Title = "Орківська сумка"
                        },
                        new
                        {
                            Id = new Guid("9f74c4e9-8818-41cf-8520-b055ad40d3f1"),
                            CreatedAt = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            Description = "Армійський пайок російської армії (умовно їстівний).",
                            EndTime = new DateTime(2025, 5, 5, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            ImageUrl = "https://i.postimg.cc/5YVRVYrN/russian-payok.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            StartingPrice = 200m,
                            Title = "Російський сухпайок"
                        },
                        new
                        {
                            Id = new Guid("6824a88e-6cc6-4708-99c7-77d96bc4828f"),
                            CreatedAt = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            Description = "Оригінальний шеврон українського підрозділу №71.",
                            EndTime = new DateTime(2025, 5, 5, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            ImageUrl = "https://i.postimg.cc/s13NHWST/shevron-Ukraine-71.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            StartingPrice = 600m,
                            Title = "Шеврон Україна 71"
                        },
                        new
                        {
                            Id = new Guid("cc5644bb-3762-4a4c-8842-a9fc93f5c73a"),
                            CreatedAt = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            Description = "Шеврон спецпідрозділу з емблемою кажана.",
                            EndTime = new DateTime(2025, 5, 5, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            ImageUrl = "https://i.postimg.cc/xqgFwd3n/tripe.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            StartingPrice = 450m,
                            Title = "Шеврон Спецназу (Тріп)"
                        },
                        new
                        {
                            Id = new Guid("bd9ebb2b-c661-4801-a15d-1603e988039a"),
                            CreatedAt = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            Description = "Комплект зброї для зенітного підрозділу в камуфляжі.",
                            EndTime = new DateTime(2025, 5, 5, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            ImageUrl = "https://i.postimg.cc/JGndMWpJ/zenitka.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 28, 7, 56, 10, 368, DateTimeKind.Utc).AddTicks(8410),
                            StartingPrice = 10000m,
                            Title = "Зенітка (комплект)"
                        });
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDonated")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4de2f39-9758-4644-9fd0-0563cd06a1c3"),
                            Amount = 1600m,
                            AuctionId = new Guid("db2b8c40-60c7-4ed1-a6cb-393be4444f77"),
                            CreatedAt = new DateTime(2025, 4, 27, 21, 56, 10, 368, DateTimeKind.Utc).AddTicks(8537),
                            IsDonated = false,
                            UserId = "62a7c1cd-e93a-4aab-a8a4-64e22210c77f"
                        },
                        new
                        {
                            Id = new Guid("f6113f49-f5e8-4bd5-9715-9d8e9de77454"),
                            Amount = 1700m,
                            AuctionId = new Guid("db2b8c40-60c7-4ed1-a6cb-393be4444f77"),
                            CreatedAt = new DateTime(2025, 4, 27, 23, 56, 10, 368, DateTimeKind.Utc).AddTicks(8537),
                            IsDonated = false,
                            UserId = "e034755d-65a9-4f2b-a661-556edac6a6b0"
                        },
                        new
                        {
                            Id = new Guid("a4a7911e-a359-44e5-acf6-81a6419b532d"),
                            Amount = 210m,
                            AuctionId = new Guid("29fe88ee-701c-42c3-9a4f-7d1926d1c23f"),
                            CreatedAt = new DateTime(2025, 4, 28, 0, 56, 10, 368, DateTimeKind.Utc).AddTicks(8537),
                            IsDonated = false,
                            UserId = "e034755d-65a9-4f2b-a661-556edac6a6b0"
                        },
                        new
                        {
                            Id = new Guid("0c21944d-93d7-4dde-b36d-4a87b85d1457"),
                            Amount = 220m,
                            AuctionId = new Guid("29fe88ee-701c-42c3-9a4f-7d1926d1c23f"),
                            CreatedAt = new DateTime(2025, 4, 28, 2, 56, 10, 368, DateTimeKind.Utc).AddTicks(8537),
                            IsDonated = false,
                            UserId = "62a7c1cd-e93a-4aab-a8a4-64e22210c77f"
                        },
                        new
                        {
                            Id = new Guid("295d15eb-05ae-4596-ace2-81257763af5f"),
                            Amount = 850m,
                            AuctionId = new Guid("d09c2220-669a-401b-8f6a-4f4f114329df"),
                            CreatedAt = new DateTime(2025, 4, 28, 1, 56, 10, 368, DateTimeKind.Utc).AddTicks(8537),
                            IsDonated = false,
                            UserId = "2a8da342-5a30-4c2a-a9f2-77bb6659c25f"
                        },
                        new
                        {
                            Id = new Guid("c4257975-ef0c-4bca-975b-d4bac08f73f7"),
                            Amount = 7100m,
                            AuctionId = new Guid("6309e613-c9d2-4bbc-b0b6-546d82d27be5"),
                            CreatedAt = new DateTime(2025, 4, 27, 22, 56, 10, 368, DateTimeKind.Utc).AddTicks(8537),
                            IsDonated = false,
                            UserId = "62a7c1cd-e93a-4aab-a8a4-64e22210c77f"
                        },
                        new
                        {
                            Id = new Guid("8461da56-1127-44e5-8c45-24bbeea25984"),
                            Amount = 550m,
                            AuctionId = new Guid("803387b4-afb3-4fcb-840a-9dd9f63fc841"),
                            CreatedAt = new DateTime(2025, 4, 28, 4, 56, 10, 368, DateTimeKind.Utc).AddTicks(8537),
                            IsDonated = false,
                            UserId = "e034755d-65a9-4f2b-a661-556edac6a6b0"
                        },
                        new
                        {
                            Id = new Guid("256cf0e6-82d0-48f2-8dfb-6351fee1d157"),
                            Amount = 450m,
                            AuctionId = new Guid("fe807746-bf07-4157-aaf4-f157ff3c6f2a"),
                            CreatedAt = new DateTime(2025, 4, 28, 3, 56, 10, 368, DateTimeKind.Utc).AddTicks(8537),
                            IsDonated = false,
                            UserId = "2a8da342-5a30-4c2a-a9f2-77bb6659c25f"
                        },
                        new
                        {
                            Id = new Guid("330f26eb-a0c9-455b-af9a-d48463168f2c"),
                            Amount = 230m,
                            AuctionId = new Guid("9f74c4e9-8818-41cf-8520-b055ad40d3f1"),
                            CreatedAt = new DateTime(2025, 4, 28, 5, 56, 10, 368, DateTimeKind.Utc).AddTicks(8537),
                            IsDonated = false,
                            UserId = "62a7c1cd-e93a-4aab-a8a4-64e22210c77f"
                        },
                        new
                        {
                            Id = new Guid("ef7cf4d3-adc9-497c-ac0d-27d6b9952eef"),
                            Amount = 700m,
                            AuctionId = new Guid("6824a88e-6cc6-4708-99c7-77d96bc4828f"),
                            CreatedAt = new DateTime(2025, 4, 28, 6, 56, 10, 368, DateTimeKind.Utc).AddTicks(8537),
                            IsDonated = false,
                            UserId = "e034755d-65a9-4f2b-a661-556edac6a6b0"
                        },
                        new
                        {
                            Id = new Guid("a3716aba-e99e-4be2-b634-87b81b6ef347"),
                            Amount = 500m,
                            AuctionId = new Guid("cc5644bb-3762-4a4c-8842-a9fc93f5c73a"),
                            CreatedAt = new DateTime(2025, 4, 28, 7, 6, 10, 368, DateTimeKind.Utc).AddTicks(8537),
                            IsDonated = false,
                            UserId = "2a8da342-5a30-4c2a-a9f2-77bb6659c25f"
                        },
                        new
                        {
                            Id = new Guid("c50b333a-82e1-42a8-b383-06282636ade8"),
                            Amount = 10500m,
                            AuctionId = new Guid("bd9ebb2b-c661-4801-a15d-1603e988039a"),
                            CreatedAt = new DateTime(2025, 4, 28, 7, 26, 10, 368, DateTimeKind.Utc).AddTicks(8537),
                            IsDonated = false,
                            UserId = "62a7c1cd-e93a-4aab-a8a4-64e22210c77f"
                        });
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "seller",
                            NormalizedName = "SELLER"
                        },
                        new
                        {
                            Id = "3",
                            Name = "buyer",
                            NormalizedName = "BUYER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "7b26038d-1a43-4248-90e1-dc7f0381d7fa",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "62a7c1cd-e93a-4aab-a8a4-64e22210c77f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "e034755d-65a9-4f2b-a661-556edac6a6b0",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "2a8da342-5a30-4c2a-a9f2-77bb6659c25f",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.Auction", b =>
                {
                    b.HasOne("CharityAuction.Domain.Entities.ApplicationUser", "Organizer")
                        .WithMany("Auctions")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.Bid", b =>
                {
                    b.HasOne("CharityAuction.Domain.Entities.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharityAuction.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Bids")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.Notification", b =>
                {
                    b.HasOne("CharityAuction.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CharityAuction.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CharityAuction.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharityAuction.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CharityAuction.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Bids");
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.Auction", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
