// <auto-generated />
using System;
using CharityAuction.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CharityAuction.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250429111758_AddValidation")]
    partial class AddValidation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CharityAuction.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CommissionBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7b26038d-1a43-4248-90e1-dc7f0381d7fa",
                            AccessFailedCount = 0,
                            Balance = 5000m,
                            CommissionBalance = 500m,
                            ConcurrencyStamp = "f00efeed-aa59-423a-94b4-8c14cda604e9",
                            CreatedAt = new DateTime(2024, 10, 29, 11, 17, 58, 27, DateTimeKind.Utc).AddTicks(1771),
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN.USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEAZ+4TjXEV59bi8N5GlJomsPhxT8eBcNxR9yb3WLc7pYZMWsXIV/7U6OBtcZzyVffg==",
                            PhoneNumberConfirmed = false,
                            PhotoUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1.jpg",
                            Role = "Admin",
                            SecurityStamp = "e4b0a243-767c-4595-83ac-9f7323b0a69b",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 4, 29, 11, 17, 58, 27, DateTimeKind.Utc).AddTicks(1771),
                            UserName = "admin.user"
                        },
                        new
                        {
                            Id = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            AccessFailedCount = 0,
                            Balance = 3000m,
                            CommissionBalance = 300m,
                            ConcurrencyStamp = "dc0e897c-0e51-49a3-ab0d-764d6a967705",
                            CreatedAt = new DateTime(2024, 10, 29, 11, 17, 58, 27, DateTimeKind.Utc).AddTicks(1771),
                            Email = "seller@example.com",
                            EmailConfirmed = true,
                            FirstName = "Seller",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "SELLER@EXAMPLE.COM",
                            NormalizedUserName = "SELLER.USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEEVdYOZ8QKkLcl/O89WcIooX0Ties81/ITGp3Cv94Mmcu/aRaffySPw6/D6nXO/UAQ==",
                            PhoneNumberConfirmed = false,
                            PhotoUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/2.jpg",
                            Role = "Seller",
                            SecurityStamp = "f4f9891d-ba98-45db-bd47-0b4a6033afbd",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 4, 29, 11, 17, 58, 27, DateTimeKind.Utc).AddTicks(1771),
                            UserName = "seller.user"
                        },
                        new
                        {
                            Id = "62a7c1cd-e93a-4aab-a8a4-64e22210c77f",
                            AccessFailedCount = 0,
                            Balance = 4000m,
                            CommissionBalance = 100m,
                            ConcurrencyStamp = "7806487c-c108-4615-9faa-1bac66527e42",
                            CreatedAt = new DateTime(2024, 10, 29, 11, 17, 58, 27, DateTimeKind.Utc).AddTicks(1771),
                            Email = "buyer1@example.com",
                            EmailConfirmed = true,
                            FirstName = "Buyer",
                            LastName = "One",
                            LockoutEnabled = false,
                            NormalizedEmail = "BUYER1@EXAMPLE.COM",
                            NormalizedUserName = "BUYER.ONE",
                            PasswordHash = "AQAAAAIAAYagAAAAEGOoiFmlEy6vW1+d90Gyk68af7C+ZJBGWCW2jICcMLpRp5PmnabFiDpWHwqd48CCGg==",
                            PhoneNumberConfirmed = false,
                            PhotoUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/3.jpg",
                            Role = "Buyer",
                            SecurityStamp = "24805840-98d2-4f98-a293-89714354d1c7",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 4, 29, 11, 17, 58, 27, DateTimeKind.Utc).AddTicks(1771),
                            UserName = "buyer.one"
                        },
                        new
                        {
                            Id = "e034755d-65a9-4f2b-a661-556edac6a6b0",
                            AccessFailedCount = 0,
                            Balance = 2500m,
                            CommissionBalance = 150m,
                            ConcurrencyStamp = "fd11840b-002e-4f13-a5a3-69eac66b1ccb",
                            CreatedAt = new DateTime(2024, 10, 29, 11, 17, 58, 27, DateTimeKind.Utc).AddTicks(1771),
                            Email = "buyer2@example.com",
                            EmailConfirmed = true,
                            FirstName = "Buyer",
                            LastName = "Two",
                            LockoutEnabled = false,
                            NormalizedEmail = "BUYER2@EXAMPLE.COM",
                            NormalizedUserName = "BUYER.TWO",
                            PasswordHash = "AQAAAAIAAYagAAAAEIWVlnaGzFYBSpM5Yww90inxfy6Fry/1YuXH0OgSI/pGU01OMW9UIUHfnqlKmUZsVA==",
                            PhoneNumberConfirmed = false,
                            PhotoUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/4.jpg",
                            Role = "Buyer",
                            SecurityStamp = "f3274cdc-ef5e-41cb-b569-23c61ca1ee40",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 4, 29, 11, 17, 58, 27, DateTimeKind.Utc).AddTicks(1771),
                            UserName = "buyer.two"
                        },
                        new
                        {
                            Id = "2a8da342-5a30-4c2a-a9f2-77bb6659c25f",
                            AccessFailedCount = 0,
                            Balance = 3500m,
                            CommissionBalance = 200m,
                            ConcurrencyStamp = "1fbb0172-699b-4cf0-a805-ada85ecbaadd",
                            CreatedAt = new DateTime(2024, 10, 29, 11, 17, 58, 27, DateTimeKind.Utc).AddTicks(1771),
                            Email = "buyer3@example.com",
                            EmailConfirmed = true,
                            FirstName = "Buyer",
                            LastName = "Three",
                            LockoutEnabled = false,
                            NormalizedEmail = "BUYER3@EXAMPLE.COM",
                            NormalizedUserName = "BUYER.THREE",
                            PasswordHash = "AQAAAAIAAYagAAAAECMh+GNNgf021AOcuajA1qLqqbEL5G/OU25v9bXDyy3ewINxNW5BC2P+oCszXk2khA==",
                            PhoneNumberConfirmed = false,
                            PhotoUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/5.jpg",
                            Role = "Buyer",
                            SecurityStamp = "aeff44bb-0214-4532-9725-6354e345467d",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 4, 29, 11, 17, 58, 27, DateTimeKind.Utc).AddTicks(1771),
                            UserName = "buyer.three"
                        });
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSold")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganizerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db2b8c40-60c7-4ed1-a6cb-393be4444f77"),
                            CreatedAt = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            Description = "Пускова установка в ідеальному стані для бойових завдань.",
                            EndTime = new DateTime(2025, 5, 6, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            ImageUrl = "https://i.postimg.cc/9rFs09QD/bazuka.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            StartingPrice = 5000m,
                            Title = "Базука"
                        },
                        new
                        {
                            Id = new Guid("29fe88ee-701c-42c3-9a4f-7d1926d1c23f"),
                            CreatedAt = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            Description = "Оптичний бінокль для спостереження на великій відстані.",
                            EndTime = new DateTime(2025, 5, 6, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            ImageUrl = "https://i.postimg.cc/Tp7FDPKC/binokl.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            StartingPrice = 800m,
                            Title = "Бінокль"
                        },
                        new
                        {
                            Id = new Guid("d09c2220-669a-401b-8f6a-4f4f114329df"),
                            CreatedAt = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            Description = "Тактична кобура Blackhawk для зручного носіння зброї.",
                            EndTime = new DateTime(2025, 5, 6, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            ImageUrl = "https://i.postimg.cc/d7dxpm4x/kobura-blackhawk.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            StartingPrice = 1200m,
                            Title = "Кобура Blackhawk"
                        },
                        new
                        {
                            Id = new Guid("6309e613-c9d2-4bbc-b0b6-546d82d27be5"),
                            CreatedAt = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            Description = "Легендарний радянський гранатомет РПГ-18 \"Муха\".",
                            EndTime = new DateTime(2025, 5, 6, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            ImageUrl = "https://i.postimg.cc/0zz3dqmx/RPG-18-Mukha.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            StartingPrice = 7000m,
                            Title = "РПГ-18 Муха"
                        },
                        new
                        {
                            Id = new Guid("803387b4-afb3-4fcb-840a-9dd9f63fc841"),
                            CreatedAt = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            Description = "Оригінальна фуражка з комплекту екіпіровки окупантів.",
                            EndTime = new DateTime(2025, 5, 6, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            ImageUrl = "https://i.postimg.cc/87xYZnBv/russian-cap.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            StartingPrice = 500m,
                            Title = "Фуражка російської армії"
                        },
                        new
                        {
                            Id = new Guid("fe807746-bf07-4157-aaf4-f157ff3c6f2a"),
                            CreatedAt = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            Description = "Типова польова сумка орків, знайдена на передовій.",
                            EndTime = new DateTime(2025, 5, 6, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            ImageUrl = "https://i.postimg.cc/K3cpKXF6/russian-orkivska-sumka.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            StartingPrice = 400m,
                            Title = "Орківська сумка"
                        },
                        new
                        {
                            Id = new Guid("9f74c4e9-8818-41cf-8520-b055ad40d3f1"),
                            CreatedAt = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            Description = "Армійський пайок російської армії (умовно їстівний).",
                            EndTime = new DateTime(2025, 5, 6, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            ImageUrl = "https://i.postimg.cc/5YVRVYrN/russian-payok.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            StartingPrice = 200m,
                            Title = "Російський сухпайок"
                        },
                        new
                        {
                            Id = new Guid("6824a88e-6cc6-4708-99c7-77d96bc4828f"),
                            CreatedAt = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            Description = "Оригінальний шеврон українського підрозділу №71.",
                            EndTime = new DateTime(2025, 5, 6, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            ImageUrl = "https://i.postimg.cc/s13NHWST/shevron-Ukraine-71.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            StartingPrice = 600m,
                            Title = "Шеврон Україна 71"
                        },
                        new
                        {
                            Id = new Guid("cc5644bb-3762-4a4c-8842-a9fc93f5c73a"),
                            CreatedAt = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            Description = "Шеврон спецпідрозділу з емблемою кажана.",
                            EndTime = new DateTime(2025, 5, 6, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            ImageUrl = "https://i.postimg.cc/xqgFwd3n/tripe.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            StartingPrice = 450m,
                            Title = "Шеврон Спецназу (Тріп)"
                        },
                        new
                        {
                            Id = new Guid("bd9ebb2b-c661-4801-a15d-1603e988039a"),
                            CreatedAt = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            Description = "Комплект зброї для зенітного підрозділу в камуфляжі.",
                            EndTime = new DateTime(2025, 5, 6, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            ImageUrl = "https://i.postimg.cc/JGndMWpJ/zenitka.jpg",
                            IsActive = true,
                            IsApproved = false,
                            IsSold = false,
                            OrganizerId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            StartTime = new DateTime(2025, 4, 29, 11, 17, 58, 267, DateTimeKind.Utc).AddTicks(4547),
                            StartingPrice = 10000m,
                            Title = "Зенітка (комплект)"
                        });
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDonated")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = new Guid("93b1e458-1668-4633-a95d-5d140b001e57"),
                            Amount = 1600m,
                            AuctionId = new Guid("db2b8c40-60c7-4ed1-a6cb-393be4444f77"),
                            CreatedAt = new DateTime(2025, 4, 29, 1, 17, 58, 267, DateTimeKind.Utc).AddTicks(4738),
                            IsDonated = false,
                            UserId = "62a7c1cd-e93a-4aab-a8a4-64e22210c77f"
                        },
                        new
                        {
                            Id = new Guid("e56172a1-808e-4d11-918f-b074e8257d20"),
                            Amount = 1700m,
                            AuctionId = new Guid("db2b8c40-60c7-4ed1-a6cb-393be4444f77"),
                            CreatedAt = new DateTime(2025, 4, 29, 3, 17, 58, 267, DateTimeKind.Utc).AddTicks(4738),
                            IsDonated = false,
                            UserId = "e034755d-65a9-4f2b-a661-556edac6a6b0"
                        },
                        new
                        {
                            Id = new Guid("4628fc21-8d04-49de-83d4-87fadf20372d"),
                            Amount = 210m,
                            AuctionId = new Guid("29fe88ee-701c-42c3-9a4f-7d1926d1c23f"),
                            CreatedAt = new DateTime(2025, 4, 29, 4, 17, 58, 267, DateTimeKind.Utc).AddTicks(4738),
                            IsDonated = false,
                            UserId = "e034755d-65a9-4f2b-a661-556edac6a6b0"
                        },
                        new
                        {
                            Id = new Guid("c52523b4-4031-4623-965c-1d323404e4a8"),
                            Amount = 220m,
                            AuctionId = new Guid("29fe88ee-701c-42c3-9a4f-7d1926d1c23f"),
                            CreatedAt = new DateTime(2025, 4, 29, 6, 17, 58, 267, DateTimeKind.Utc).AddTicks(4738),
                            IsDonated = false,
                            UserId = "62a7c1cd-e93a-4aab-a8a4-64e22210c77f"
                        },
                        new
                        {
                            Id = new Guid("d37829b6-bdbb-4f1c-8693-bdcf050728da"),
                            Amount = 850m,
                            AuctionId = new Guid("d09c2220-669a-401b-8f6a-4f4f114329df"),
                            CreatedAt = new DateTime(2025, 4, 29, 5, 17, 58, 267, DateTimeKind.Utc).AddTicks(4738),
                            IsDonated = false,
                            UserId = "2a8da342-5a30-4c2a-a9f2-77bb6659c25f"
                        },
                        new
                        {
                            Id = new Guid("1f43dfee-a53e-4f77-935c-367d85aa5b13"),
                            Amount = 7100m,
                            AuctionId = new Guid("6309e613-c9d2-4bbc-b0b6-546d82d27be5"),
                            CreatedAt = new DateTime(2025, 4, 29, 2, 17, 58, 267, DateTimeKind.Utc).AddTicks(4738),
                            IsDonated = false,
                            UserId = "62a7c1cd-e93a-4aab-a8a4-64e22210c77f"
                        },
                        new
                        {
                            Id = new Guid("36471d8c-800b-4603-8a8d-40629d119406"),
                            Amount = 550m,
                            AuctionId = new Guid("803387b4-afb3-4fcb-840a-9dd9f63fc841"),
                            CreatedAt = new DateTime(2025, 4, 29, 8, 17, 58, 267, DateTimeKind.Utc).AddTicks(4738),
                            IsDonated = false,
                            UserId = "e034755d-65a9-4f2b-a661-556edac6a6b0"
                        },
                        new
                        {
                            Id = new Guid("da4c7c06-4978-4616-bf78-cce057727c6a"),
                            Amount = 450m,
                            AuctionId = new Guid("fe807746-bf07-4157-aaf4-f157ff3c6f2a"),
                            CreatedAt = new DateTime(2025, 4, 29, 7, 17, 58, 267, DateTimeKind.Utc).AddTicks(4738),
                            IsDonated = false,
                            UserId = "2a8da342-5a30-4c2a-a9f2-77bb6659c25f"
                        },
                        new
                        {
                            Id = new Guid("f7026819-8e05-4bcb-8676-e153d1b8e0bd"),
                            Amount = 230m,
                            AuctionId = new Guid("9f74c4e9-8818-41cf-8520-b055ad40d3f1"),
                            CreatedAt = new DateTime(2025, 4, 29, 9, 17, 58, 267, DateTimeKind.Utc).AddTicks(4738),
                            IsDonated = false,
                            UserId = "62a7c1cd-e93a-4aab-a8a4-64e22210c77f"
                        },
                        new
                        {
                            Id = new Guid("fc6fa5c1-798b-47c9-a271-c65270824a0a"),
                            Amount = 700m,
                            AuctionId = new Guid("6824a88e-6cc6-4708-99c7-77d96bc4828f"),
                            CreatedAt = new DateTime(2025, 4, 29, 10, 17, 58, 267, DateTimeKind.Utc).AddTicks(4738),
                            IsDonated = false,
                            UserId = "e034755d-65a9-4f2b-a661-556edac6a6b0"
                        },
                        new
                        {
                            Id = new Guid("59bad92d-8bce-4231-8345-637bafed40df"),
                            Amount = 500m,
                            AuctionId = new Guid("cc5644bb-3762-4a4c-8842-a9fc93f5c73a"),
                            CreatedAt = new DateTime(2025, 4, 29, 10, 27, 58, 267, DateTimeKind.Utc).AddTicks(4738),
                            IsDonated = false,
                            UserId = "2a8da342-5a30-4c2a-a9f2-77bb6659c25f"
                        },
                        new
                        {
                            Id = new Guid("0391b8f6-e8fa-4659-894f-ee1ac177cc6b"),
                            Amount = 10500m,
                            AuctionId = new Guid("bd9ebb2b-c661-4801-a15d-1603e988039a"),
                            CreatedAt = new DateTime(2025, 4, 29, 10, 47, 58, 267, DateTimeKind.Utc).AddTicks(4738),
                            IsDonated = false,
                            UserId = "62a7c1cd-e93a-4aab-a8a4-64e22210c77f"
                        });
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Seller",
                            NormalizedName = "SELLER"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Buyer",
                            NormalizedName = "BUYER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "7b26038d-1a43-4248-90e1-dc7f0381d7fa",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "62a7c1cd-e93a-4aab-a8a4-64e22210c77f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "e034755d-65a9-4f2b-a661-556edac6a6b0",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "2a8da342-5a30-4c2a-a9f2-77bb6659c25f",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.Auction", b =>
                {
                    b.HasOne("CharityAuction.Domain.Entities.ApplicationUser", "Organizer")
                        .WithMany("Auctions")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.Bid", b =>
                {
                    b.HasOne("CharityAuction.Domain.Entities.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharityAuction.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Bids")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.Notification", b =>
                {
                    b.HasOne("CharityAuction.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CharityAuction.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CharityAuction.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharityAuction.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CharityAuction.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Bids");
                });

            modelBuilder.Entity("CharityAuction.Domain.Entities.Auction", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
